# Generated by Django 4.1.5 on 2023-01-13 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notices", "0002_noticefile"),
    ]

    operations = [
        migrations.RenameField(
            model_name="noticefile",
            old_name="title",
            new_name="notice",
        ),
        migrations.AddField(
            model_name="noticefile",
            name="file_name",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
