# Generated by Django 4.1.5 on 2023-01-14 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notices", "0003_rename_title_noticefile_notice_noticefile_file_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="noticefile",
            name="file_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
