# Generated by Django 4.1.5 on 2023-01-14 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notices", "0004_alter_noticefile_file_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="noticefile",
            name="file_name",
        ),
    ]
