# Generated by Django 4.1.5 on 2023-01-14 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("notices", "0005_remove_noticefile_file_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="noticefile",
            name="notice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="files",
                to="notices.notice",
            ),
        ),
    ]
