# Generated by Django 4.1.5 on 2023-01-15 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notices", "0007_category_notice_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notice",
            name="author",
            field=models.CharField(default="admin", max_length=50),
        ),
    ]
