# Generated by Django 4.1.5 on 2023-01-15 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notices", "0008_alter_notice_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="noticefile",
            name="doc_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
