# Generated by Django 4.1.5 on 2023-01-16 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notices", "0009_noticefile_doc_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notice",
            options={"ordering": ("-updated_at",)},
        ),
    ]
