# Generated by Django 4.1.5 on 2023-01-19 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("notices", "0011_author_remove_notice_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="notice",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notice_author_list",
                to="notices.author",
            ),
        ),
    ]
