# Generated by Django 4.1.5 on 2023-01-20 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notices", "0013_notice_slug_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="author",
            name="address1",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="author",
            name="department",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="author",
            name="first_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="author",
            name="last_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="author",
            name="post",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
