# Generated by Django 4.1.5 on 2023-01-20 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notices", "0014_author_address_author_address1_author_department_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="email",
            field=models.EmailField(
                blank=True, default=".govt.lc", max_length=254, null=True
            ),
        ),
        migrations.AlterField(
            model_name="author",
            name="fax",
            field=models.CharField(blank=True, default="758", max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="author",
            name="tel",
            field=models.CharField(blank=True, default="758", max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="author",
            name="tel1",
            field=models.CharField(blank=True, default="758", max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="author",
            name="tel2",
            field=models.CharField(blank=True, default="758", max_length=15, null=True),
        ),
    ]
