# Generated by Django 4.1.5 on 2023-01-20 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "notices",
            "0015_alter_author_email_alter_author_fax_alter_author_tel_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="notice",
            old_name="slug_name",
            new_name="slug",
        ),
    ]
