# Generated by Django 4.1.5 on 2023-01-20 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notices", "0016_rename_slug_name_notice_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notice",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="notice",
            name="title",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
