# Generated by Django 4.1.5 on 2023-01-20 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notices", "0017_alter_notice_slug_alter_notice_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="category",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="noticefile",
            name="doc_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
