# Generated by Django 4.1.5 on 2023-01-22 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("notices", "0019_notice_is_draft_notice_is_published"),
    ]

    operations = [
        migrations.CreateModel(
            name="NoticeStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterModelOptions(
            name="notice",
            options={"ordering": ("-created_at",)},
        ),
        migrations.RemoveField(
            model_name="notice",
            name="is_draft",
        ),
        migrations.RemoveField(
            model_name="notice",
            name="is_published",
        ),
        migrations.AddField(
            model_name="notice",
            name="status",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="notices.noticestatus",
            ),
        ),
    ]
