# Generated by Django 4.1.5 on 2023-01-26 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notices", "0022_alter_notice_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="author",
            name="fax",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="author",
            name="tel",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="author",
            name="tel1",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="author",
            name="tel2",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
